#!/bin/sh

vulcanize --csp -o demo-vulcanize.html demo.html

mkdir -p libs/polymer
mkdir -p libs/webcomponentsjs

cp ../../polymer/polymer.js libs/polymer/polymer.js
cp ../../webcomponentsjs/webcomponents.js libs/webcomponentsjs/webcomponents.js

sed -i.bak 's/\.\.\/\.\.\//libs\//g' demo-vulcanize.html
rm demo-vulcanize.html.bak
